name: Continuous Integration
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
env:
  LC_CTYPE: C.UTF-8
  CMAKE_COLOR_DIAGNOSTICS: ON
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt install cmake g++ pkg-config libogg-dev ffmpeg libtest-harness-perl libtest-deep-perl liblist-moreutils-perl libtest-utf8-perl
    - name: Build
      env:
        CXX: g++
        CXXFLAGS: -D_FORTIFY_SOURCE=3 -D_GLIBCXX_ASSERTIONS -D_GLIBCXX_DEBUG -O2 -flto=auto -g -Wall -Wextra -Werror=format-security -fstack-protector-strong -fstack-clash-protection -fcf-protection -fsanitize=address,undefined
        LDFLAGS: -fsanitize=address,undefined
      run: |
        cmake -B target -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
        cmake --build target
    - name: Test
      run: |
        cmake --build target --target check
